/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "02_04_serial_adder_with_vld.sv:5.1-66.10" *)
module serial_adder_with_vld(clk, rst, vld, a, b, last, sum);
  (* src = "02_04_serial_adder_with_vld.sv:31.3-47.6" *)
  wire _00_;
  (* src = "02_04_serial_adder_with_vld.sv:31.3-47.6" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "02_04_serial_adder_with_vld.sv:10.10-10.11" *)
  input a;
  wire a;
  (* src = "02_04_serial_adder_with_vld.sv:11.10-11.11" *)
  input b;
  wire b;
  (* src = "02_04_serial_adder_with_vld.sv:16.8-16.12" *)
  wire calc;
  (* src = "02_04_serial_adder_with_vld.sv:20.7-20.16" *)
  reg carry_reg = 1'h0;
  (* src = "02_04_serial_adder_with_vld.sv:7.10-7.13" *)
  input clk;
  wire clk;
  (* src = "02_04_serial_adder_with_vld.sv:12.10-12.14" *)
  input last;
  wire last;
  (* src = "02_04_serial_adder_with_vld.sv:8.10-8.13" *)
  input rst;
  wire rst;
  (* src = "02_04_serial_adder_with_vld.sv:13.10-13.13" *)
  output sum;
  wire sum;
  (* src = "02_04_serial_adder_with_vld.sv:21.7-21.14" *)
  reg sum_reg = 1'h0;
  (* src = "02_04_serial_adder_with_vld.sv:9.10-9.13" *)
  input vld;
  wire vld;
  assign _03_ = ~(last & vld);
  assign _02_ = vld | ~(_03_);
  assign sum = sum_reg & ~(_03_);
  assign _04_ = ~(carry_reg & a);
  assign _05_ = ~(carry_reg ^ a);
  assign _06_ = b & ~(_05_);
  assign _07_ = _04_ & ~(_06_);
  assign _00_ = vld & ~(_07_);
  assign _08_ = _05_ ^ b;
  assign _01_ = vld & ~(_08_);
  (* src = "02_04_serial_adder_with_vld.sv:31.3-47.6" *)
  always @(posedge clk)
    if (rst) carry_reg <= 1'h0;
    else if (_02_) carry_reg <= _00_;
  (* src = "02_04_serial_adder_with_vld.sv:31.3-47.6" *)
  always @(posedge clk)
    if (rst) sum_reg <= 1'h0;
    else if (_02_) sum_reg <= _01_;
  assign calc = vld;
endmodule
