/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* src = "d2.sv:2.1-41.10" *)
module shift_register_with_valid(clk, rst, in_vld, in_data, out_vld, out_data);
  (* src = "d2.sv:7.26-7.29" *)
  input clk;
  wire clk;
  (* src = "d2.sv:11.26-11.33" *)
  input [7:0] in_data;
  wire [7:0] in_data;
  (* src = "d2.sv:10.26-10.32" *)
  input in_vld;
  wire in_vld;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[0] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[1] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[2] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[3] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[4] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[5] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[6] ;
  (* src = "d2.sv:17.23-17.31" *)
  reg [7:0] \mem_data[7] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[0] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[1] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[2] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[3] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[4] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[5] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[6] ;
  (* src = "d2.sv:16.9-16.16" *)
  reg \mem_vld[7] ;
  (* src = "d2.sv:14.26-14.34" *)
  output [7:0] out_data;
  wire [7:0] out_data;
  (* src = "d2.sv:13.26-13.33" *)
  output out_vld;
  wire out_vld;
  (* src = "d2.sv:8.26-8.29" *)
  input rst;
  wire rst;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[7]  <= 1'h0;
    else \mem_vld[7]  <= \mem_vld[6] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[0]  <= 1'h0;
    else \mem_vld[0]  <= in_vld;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[1]  <= 1'h0;
    else \mem_vld[1]  <= \mem_vld[0] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[2]  <= 1'h0;
    else \mem_vld[2]  <= \mem_vld[1] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[3]  <= 1'h0;
    else \mem_vld[3]  <= \mem_vld[2] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[4]  <= 1'h0;
    else \mem_vld[4]  <= \mem_vld[3] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[5]  <= 1'h0;
    else \mem_vld[5]  <= \mem_vld[4] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_vld[6]  <= 1'h0;
    else \mem_vld[6]  <= \mem_vld[5] ;
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [0] <= 1'h0;
    else if (in_vld) \mem_data[0] [0] <= in_data[0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [1] <= 1'h0;
    else if (in_vld) \mem_data[0] [1] <= in_data[1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [2] <= 1'h0;
    else if (in_vld) \mem_data[0] [2] <= in_data[2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [3] <= 1'h0;
    else if (in_vld) \mem_data[0] [3] <= in_data[3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [4] <= 1'h0;
    else if (in_vld) \mem_data[0] [4] <= in_data[4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [5] <= 1'h0;
    else if (in_vld) \mem_data[0] [5] <= in_data[5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [6] <= 1'h0;
    else if (in_vld) \mem_data[0] [6] <= in_data[6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[0] [7] <= 1'h0;
    else if (in_vld) \mem_data[0] [7] <= in_data[7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [0] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [0] <= \mem_data[0] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [1] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [1] <= \mem_data[0] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [2] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [2] <= \mem_data[0] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [3] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [3] <= \mem_data[0] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [4] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [4] <= \mem_data[0] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [5] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [5] <= \mem_data[0] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [6] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [6] <= \mem_data[0] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[1] [7] <= 1'h0;
    else if (\mem_vld[0] ) \mem_data[1] [7] <= \mem_data[0] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [0] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [0] <= \mem_data[1] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [1] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [1] <= \mem_data[1] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [2] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [2] <= \mem_data[1] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [3] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [3] <= \mem_data[1] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [4] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [4] <= \mem_data[1] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [5] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [5] <= \mem_data[1] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [6] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [6] <= \mem_data[1] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[2] [7] <= 1'h0;
    else if (\mem_vld[1] ) \mem_data[2] [7] <= \mem_data[1] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [0] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [0] <= \mem_data[2] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [1] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [1] <= \mem_data[2] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [2] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [2] <= \mem_data[2] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [3] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [3] <= \mem_data[2] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [4] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [4] <= \mem_data[2] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [5] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [5] <= \mem_data[2] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [6] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [6] <= \mem_data[2] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[3] [7] <= 1'h0;
    else if (\mem_vld[2] ) \mem_data[3] [7] <= \mem_data[2] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [0] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [0] <= \mem_data[3] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [1] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [1] <= \mem_data[3] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [2] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [2] <= \mem_data[3] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [3] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [3] <= \mem_data[3] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [4] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [4] <= \mem_data[3] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [5] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [5] <= \mem_data[3] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [6] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [6] <= \mem_data[3] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[4] [7] <= 1'h0;
    else if (\mem_vld[3] ) \mem_data[4] [7] <= \mem_data[3] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [0] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [0] <= \mem_data[4] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [1] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [1] <= \mem_data[4] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [2] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [2] <= \mem_data[4] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [3] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [3] <= \mem_data[4] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [4] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [4] <= \mem_data[4] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [5] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [5] <= \mem_data[4] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [6] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [6] <= \mem_data[4] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[5] [7] <= 1'h0;
    else if (\mem_vld[4] ) \mem_data[5] [7] <= \mem_data[4] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [0] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [0] <= \mem_data[5] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [1] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [1] <= \mem_data[5] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [2] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [2] <= \mem_data[5] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [3] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [3] <= \mem_data[5] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [4] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [4] <= \mem_data[5] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [5] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [5] <= \mem_data[5] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [6] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [6] <= \mem_data[5] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[6] [7] <= 1'h0;
    else if (\mem_vld[5] ) \mem_data[6] [7] <= \mem_data[5] [7];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [0] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [0] <= \mem_data[6] [0];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [1] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [1] <= \mem_data[6] [1];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [2] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [2] <= \mem_data[6] [2];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [3] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [3] <= \mem_data[6] [3];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [4] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [4] <= \mem_data[6] [4];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [5] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [5] <= \mem_data[6] [5];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [6] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [6] <= \mem_data[6] [6];
  (* \always_ff  = 32'd1 *)
  (* src = "d2.sv:19.5-37.8" *)
  always @(posedge clk)
    if (rst) \mem_data[7] [7] <= 1'h0;
    else if (\mem_vld[6] ) \mem_data[7] [7] <= \mem_data[6] [7];
  assign out_data = \mem_data[7] ;
  assign out_vld = \mem_vld[7] ;
endmodule
