/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "cnba_tr_s.v:17.1-84.10" *)
module serial_comparator_most_significant_first(clk, rst, a, b, a_less_b, a_eq_b, a_greater_b);
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  wire _00_;
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "cnba_tr_s.v:21.10-21.11" *)
  input a;
  wire a;
  (* src = "cnba_tr_s.v:24.10-24.16" *)
  output a_eq_b;
  wire a_eq_b;
  (* src = "cnba_tr_s.v:25.10-25.21" *)
  output a_greater_b;
  wire a_greater_b;
  (* src = "cnba_tr_s.v:23.10-23.18" *)
  output a_less_b;
  wire a_less_b;
  (* src = "cnba_tr_s.v:22.10-22.11" *)
  input b;
  wire b;
  (* src = "cnba_tr_s.v:19.10-19.13" *)
  input clk;
  wire clk;
  (* src = "cnba_tr_s.v:27.7-27.21" *)
  reg is_first_stage;
  (* src = "cnba_tr_s.v:28.7-28.17" *)
  reg old_res_eq;
  (* src = "cnba_tr_s.v:28.19-28.29" *)
  reg old_res_le;
  (* src = "cnba_tr_s.v:35.18-35.27" *)
  reg result_eq;
  (* src = "cnba_tr_s.v:35.7-35.16" *)
  reg result_le;
  (* src = "cnba_tr_s.v:20.10-20.13" *)
  input rst;
  wire rst;
  assign _02_ = result_le & ~(result_eq);
  assign _03_ = b & ~(a);
  assign a_less_b = is_first_stage ? _03_ : _02_;
  assign _04_ = a | ~(b);
  assign _05_ = ~(result_le | result_eq);
  assign a_greater_b = is_first_stage ? _04_ : _05_;
  assign _06_ = ~(b ^ a);
  assign a_eq_b = is_first_stage ? _06_ : result_eq;
  assign _01_ = old_res_eq ? _03_ : old_res_le;
  assign _07_ = is_first_stage ? _03_ : _01_;
  assign _00_ = _06_ & old_res_eq;
  assign _08_ = is_first_stage ? _06_ : _00_;
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  always @(posedge clk)
    if (!rst) result_eq <= _00_;
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  always @(posedge clk)
    is_first_stage <= rst;
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  always @(posedge clk)
    if (rst) old_res_eq <= 1'h0;
    else old_res_eq <= _08_;
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  always @(posedge clk)
    if (rst) old_res_le <= 1'h0;
    else old_res_le <= _07_;
  (* src = "cnba_tr_s.v:43.3-72.6" *)
  always @(posedge clk)
    if (!rst) result_le <= _01_;
endmodule
