/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "one_cycle_pulse_detector.v:1.1-24.10" *)
module one_cycle_pulse_detector(clk, rst, a, detected, cur_sequence);
  (* src = "one_cycle_pulse_detector.v:9.3-22.6" *)
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "one_cycle_pulse_detector.v:4.11-4.12" *)
  input a;
  wire a;
  (* src = "one_cycle_pulse_detector.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "one_cycle_pulse_detector.v:6.22-6.34" *)
  output [2:0] cur_sequence;
  wire [2:0] cur_sequence;
  (* src = "one_cycle_pulse_detector.v:5.16-5.24" *)
  output detected;
  wire detected;
  (* src = "one_cycle_pulse_detector.v:3.11-3.14" *)
  input rst;
  wire rst;
  INV_X1 _09_ (
    .A(rst),
    .ZN(_02_)
  );
  NOR3_X1 _10_ (
    .A1(a),
    .A2(_01_),
    .A3(cur_sequence[1]),
    .ZN(_00_)
  );
  INV_X1 _11_ (
    .A(rst),
    .ZN(_03_)
  );
  INV_X1 _12_ (
    .A(rst),
    .ZN(_04_)
  );
  INV_X1 _13_ (
    .A(rst),
    .ZN(_05_)
  );
  (* src = "one_cycle_pulse_detector.v:9.3-22.6" *)
  DFFR_X1 _14_ (
    .CK(clk),
    .D(a),
    .Q(cur_sequence[0]),
    .QN(_01_),
    .RN(_02_)
  );
  (* src = "one_cycle_pulse_detector.v:9.3-22.6" *)
  DFFR_X1 _15_ (
    .CK(clk),
    .D(cur_sequence[0]),
    .Q(cur_sequence[1]),
    .QN(_08_),
    .RN(_03_)
  );
  (* src = "one_cycle_pulse_detector.v:9.3-22.6" *)
  DFFR_X1 _16_ (
    .CK(clk),
    .D(cur_sequence[1]),
    .Q(cur_sequence[2]),
    .QN(_07_),
    .RN(_04_)
  );
  (* src = "one_cycle_pulse_detector.v:9.3-22.6" *)
  DFFR_X1 _17_ (
    .CK(clk),
    .D(_00_),
    .Q(detected),
    .QN(_06_),
    .RN(_05_)
  );
endmodule
